Repository KULeuven-MICAS/snax_cluster, pull requests merged in 2024-05, with the labels that each got.

#104 chisel refactoring to enable split main <-> test
  .github/workflows/scala-unit-test.yml
  hw/chisel/.gitignore
  hw/chisel/README.md
  hw/chisel/doc/streamer.md
  hw/chisel/src/main/scala/snax/csr_manager/CsrManager.scala
  hw/chisel/src/main/scala/snax/streamer/DataMover.scala
  hw/chisel/src/main/scala/snax/streamer/DataReader.scala
  hw/chisel/src/main/scala/snax/streamer/DataWriter.scala
  hw/chisel/src/main/scala/snax/streamer/FIFO.scala
  hw/chisel/src/main/scala/snax/streamer/Parameters.scala
  hw/chisel/src/main/scala/snax/streamer/SpatialAddrGenUnit.scala
  hw/chisel/src/main/scala/snax/streamer/Streamer.scala
  hw/chisel/src/main/scala/snax/streamer/StreamerInstanceParameters.scala
  hw/chisel/src/main/scala/snax/streamer/StreamerTop.scala
  hw/chisel/src/main/scala/snax/streamer/TemporalAddrGenUnit.scala
  hw/chisel/src/test/scala/snax/csr_manager/CsrManagerGenerate.scala
  hw/chisel/src/test/scala/snax/csr_manager/CsrManagerTestParameters.scala
  hw/chisel/src/test/scala/snax/streamer/DataReaderTest.scala
  hw/chisel/src/test/scala/snax/streamer/DataWriterTest.scala
  hw/chisel/src/test/scala/snax/streamer/FIFOTest.scala
  hw/chisel/src/test/scala/snax/streamer/SpatialAddrGenUnitTest.scala
  hw/chisel/src/test/scala/snax/streamer/StreamerTest.scala
  hw/chisel/src/test/scala/snax/streamer/StreamerTestParameter.scala
  hw/chisel/src/test/scala/snax/streamer/StreamerTopGenerate.scala
  hw/chisel/src/test/scala/snax/streamer/StreamerTopTest.scala
  hw/chisel/src/test/scala/snax/streamer/TemporalAddrGenUnitTest.scala
Labels: clean up

#105 Add SNAX simple ALU example
  .github/workflows/ci.yml
  .github/workflows/gen.yml
  Bender.yml
  docs/schema/snitch_cluster.schema.json
  hw/snax_alu/doc/snax_alu.md
  hw/snax_alu/src/snax_alu_csr.sv
  hw/snax_alu/src/snax_alu_pe.sv
  hw/snax_alu/src/snax_alu_shell_wrapper.sv
  hw/snax_util/src/snax_acc_mux_demux.sv
  hw/snax_util/src/snax_csr_mux_demux.sv
  hw/snax_util/src/snax_intf_translator.sv
  hw/snitch_cluster/src/snitch_cluster.sv
  hw/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
  hw/templates/csrman_param_gen.scala.tpl
  hw/templates/snax_acc_wrapper.sv.tpl
  hw/templates/snax_accelerator_top_wrapper.sv.tpl
  hw/templates/snax_csrman_wrapper.sv.tpl
  hw/templates/snax_streamer_wrapper.sv.tpl
  hw/templates/stream_param_gen.scala.tpl
  target/snitch_cluster/Makefile
  target/snitch_cluster/cfg/snax-alu.hjson
  target/snitch_cluster/cfg/snax-gemm.hjson
  target/snitch_cluster/cfg/snax-mac-mult.hjson
  target/snitch_cluster/cfg/snax-mac.hjson
  target/snitch_cluster/cfg/snax-streamer-gemm.hjson
  util/chiselgen/chiselgen.py
  util/wrappergen/wrappergen.py
Labels: enhancement

#117 Add accelerator design tutorial
  docs/tutorial/accelerator_design.md
  docs/tutorial/architectural_overview.md
  hw/snax_alu/doc/snax_alu.md
Labels: documentation

#118 Add CSR manager discussion
  docs/tutorial/accelerator_design.md
  docs/tutorial/csrman_design.md
  hw/templates/snax_csrman_wrapper.sv.tpl
Labels: documentation

#121 Add streamer tutorial
  docs/tutorial/accelerator_design.md
  docs/tutorial/streamer_design.md
Labels: documentation

#123 Add build documentation
  docs/tutorial/accelerator_design.md
  docs/tutorial/build_system.md
  docs/tutorial/connect_shell.md
  docs/tutorial/csrman_design.md
  docs/tutorial/introduction.md
  docs/tutorial/streamer_design.md
Labels: documentation

#124 Add programming tutorial
  docs/tutorial/programming.md
  target/snitch_cluster/sw/apps/snax-alu/src/snax-alu.c
Labels: documentation

#122 Add streamer simd
  .github/workflows/ci.yml
  Bender.yml
  target/snitch_cluster/Makefile
  target/snitch_cluster/cfg/snax-streamer-simd.hjson
  target/snitch_cluster/sw/Makefile
  target/snitch_cluster/sw/apps/Makefile
  target/snitch_cluster/sw/apps/snax-streamer-simd/Makefile
  target/snitch_cluster/sw/apps/snax-streamer-simd/data/Makefile
  target/snitch_cluster/sw/apps/snax-streamer-simd/data/datagen.py
  target/snitch_cluster/sw/apps/snax-streamer-simd/data/params.hjson
  target/snitch_cluster/sw/apps/snax-streamer-simd/src/snax-streamer-simd.c
  target/snitch_cluster/sw/snax-streamer-simd-run.yaml
  target/snitch_cluster/sw/snax/streamer-simd/Makefile
  target/snitch_cluster/sw/snax/streamer-simd/include/snax-streamer-simd-lib.h
  target/snitch_cluster/sw/snax/streamer-simd/src/snax-streamer-simd-lib.c
Labels: enhancement

#128 Fix introduction page
  docs/tutorial/introduction.md
Labels: documentation

#126 Add data reshuffler
  .github/workflows/ci.yml
  Bender.yml
  hw/snax_data_reshuffler/src/data_reshuffler.sv
  hw/snax_data_reshuffler/src/snax_data_reshuffler_shell_wrapper.sv
  target/snitch_cluster/Makefile
  target/snitch_cluster/cfg/snax-data-reshuffler.hjson
  target/snitch_cluster/sw/Makefile
  target/snitch_cluster/sw/apps/Makefile
  target/snitch_cluster/sw/apps/snax-data-reshuffler/Makefile
  target/snitch_cluster/sw/apps/snax-data-reshuffler/data/Makefile
  target/snitch_cluster/sw/apps/snax-data-reshuffler/data/datagen.py
  target/snitch_cluster/sw/apps/snax-data-reshuffler/data/params.hjson
  target/snitch_cluster/sw/apps/snax-data-reshuffler/src/snax-data-reshuffler.c
  target/snitch_cluster/sw/snax-data-reshuffler-run.yaml
  target/snitch_cluster/sw/snax/data-reshuffler/Makefile
  target/snitch_cluster/sw/snax/data-reshuffler/include/snax-data-reshuffler-lib.h
  target/snitch_cluster/sw/snax/data-reshuffler/src/snax-data-reshuffler-lib.c
Labels: enhancement

#125 Add other tools tutorial
  docs/tutorial/other_tools.md
Labels: documentation

#132 Add fixes from initial feedback
  docs/tutorial/accelerator_design.md
  docs/tutorial/architectural_overview.md
  docs/tutorial/build_system.md
  docs/tutorial/csrman_design.md
  docs/tutorial/introduction.md
  docs/tutorial/more_designs.md
  docs/tutorial/other_tools.md
  docs/tutorial/streamer_design.md
  docs/ug/getting_started.md
  hw/snax_alu/doc/snax_alu.md
  hw/snax_alu/src/snax_alu_csr.sv
  mkdocs.yml
  target/snitch_cluster/cfg/snax-alu.hjson
  util/container/README.md
Labels: documentation

#127 Add summary and hands-on exercise
  docs/tutorial/introduction.md
  docs/tutorial/summary_and_exercise.md
  mkdocs.yml
Labels: documentation
