Repository KULeuven-MICAS/snax_cluster, pull requests merged in 2024-07, with the labels that each got.

#172 Fix cluster renaming required for multiple cluster generation
  Bender.yml
  hw/templates/testharness.sv.tpl
  target/snitch_cluster/Makefile
  target/snitch_cluster/cfg/default.hjson
  target/snitch_cluster/cfg/snax-alu.hjson
  target/snitch_cluster/cfg/snax-data-reshuffler.hjson
  target/snitch_cluster/cfg/snax-gemm.hjson
  target/snitch_cluster/cfg/snax-mac-mult.hjson
  target/snitch_cluster/cfg/snax-mac.hjson
  target/snitch_cluster/cfg/snax-streamer-gemm-add-c.hjson
  target/snitch_cluster/cfg/snax-streamer-gemm-conv.hjson
  target/snitch_cluster/cfg/snax-streamer-gemm.hjson
  target/snitch_cluster/cfg/snax-streamer-gemmX.hjson
  target/snitch_cluster/cfg/snax-streamer-simd.hjson
  target/snitch_cluster/cfg/snax-wide-gemm-data-reshuffler.hjson
  target/snitch_cluster/test/testharness.sv
  util/clustergen.py
  util/wrappergen/wrappergen.py
Labels: enhancement

#198 Move memories into modules for PNR power routing
  Bender.yml
  hw/snitch_cluster/src/snitch_cluster.sv
  hw/snitch_cluster/src/snitch_data_mem.sv
  hw/snitch_icache/src/snitch_icache_data.sv
  hw/snitch_icache/src/snitch_icache_lookup.sv
  hw/snitch_icache/src/snitch_icache_tag.sv
Labels: freaking urgent, clean up

#202 csr soft_switch function in snrt.h
  sw/snRuntime/src/csr.h
  target/snitch_cluster/sw/runtime/rtl-generic/src/snrt.h
  target/snitch_cluster/sw/runtime/rtl/src/snrt.h
  target/snitch_cluster/sw/snax/xdma/include/snax-xdma-lib.h
  target/snitch_cluster/sw/snax/xdma/src/snax-xdma-lib.c
Labels: clean up

#203 Update xdma to support disabling any number of streamer channels
  hw/chisel/src/main/scala/snax/xdma/DesignParams/DesignParams.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaStreamer/AddressGenUnit.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaStreamer/DataRequestor.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaStreamer/DataResponser.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaStreamer/Reader.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaStreamer/Writer.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaTop/xdmaTop.scala
  hw/chisel/src/test/scala/snax/xdma/xdmaStreamer/AddressGenUnitTester.scala
  hw/chisel/src/test/scala/snax/xdma/xdmaTop/xdmaTopTester.scala
  target/snitch_cluster/sw/apps/snax-xdma-memset/Makefile
  target/snitch_cluster/sw/apps/snax-xdma-memset/data/data.h
  target/snitch_cluster/sw/apps/snax-xdma-memset/src/snax-xdma-memset.c
  target/snitch_cluster/sw/snax/xdma/include/snax-xdma-csr-addr.h
  target/snitch_cluster/sw/snax/xdma/include/snax-xdma-lib.h
  target/snitch_cluster/sw/snax/xdma/src/snax-xdma-lib.c
Labels: enhancement, clean up
