Repository KULeuven-MICAS/snax_cluster, pull requests merged in 2024-09, with the labels that each got.

#304 Change bender target generation to come from the configuration files
  target/snitch_cluster/Makefile
  target/snitch_cluster/cfg/default.hjson
  target/snitch_cluster/cfg/snax-alu.hjson
  target/snitch_cluster/cfg/snax-hypercorex.hjson
  target/snitch_cluster/cfg/snax-kul-cluster-mixed-narrow-wide-xdma.hjson
  target/snitch_cluster/cfg/snax-kul-cluster-mixed-narrow-wide.hjson
  target/snitch_cluster/cfg/snax-mac-mult.hjson
  target/snitch_cluster/cfg/snax-mac.hjson
  target/snitch_cluster/cfg/snax-streamer-gemm-add-c.hjson
  target/snitch_cluster/cfg/snax-streamer-gemm.hjson
  util/snaxgen/snaxgen.py
Labels: enhancement, clean up

#308 Initial add of SNAX DIMC
  .github/workflows/ci.yml
  Bender.yml
  hw/snax_dimc/snax_dimc_shell_wrapper.sv
  target/snitch_cluster/cfg/snax-dimc.hjson
Labels: enhancement

#311 [WIP] Fix templates and config for file generation
  Bender.yml
  hw/chisel/src/main/scala/snax/streamer/Streamer.scala
  hw/templates/snax_acc_wrapper.sv.tpl
  hw/templates/snax_streamer_wrapper.sv.tpl
  hw/templates/stream_param_gen.scala.tpl
  target/snitch_cluster/cfg/snax-alu.hjson
  target/snitch_cluster/cfg/snax-streamer-gemm-add-c.hjson
  target/snitch_cluster/cfg/snax-streamer-gemm.hjson
  util/snaxgen/snaxgen.py
Labels: enhancement, clean up

#310 Taking out license tag for the configuration templates.
  hw/templates/config_impl.txt.tpl
  hw/templates/config_spec.txt.tpl
Labels: clean up

#314 Fix ALU test to pass
  .github/workflows/ci.yml
  target/snitch_cluster/cfg/snax-alu.hjson
  target/snitch_cluster/sw/Makefile
  target/snitch_cluster/sw/apps/Makefile
  target/snitch_cluster/sw/apps/snax-alu/Makefile
  target/snitch_cluster/sw/apps/snax-alu/src/snax-alu.c
  target/snitch_cluster/sw/snax/snax-alu/Makefile
  target/snitch_cluster/sw/snax/snax-alu/include/snax-alu-lib.h
  target/snitch_cluster/sw/snax/snax-alu/src/snax-alu-lib.c
  util/snaxgen/snaxgen.py
Labels: bug, clean up

#322 Add ROM enable for Hypercorex
  hw/snax_hypercorex/snax_hypercorex_shell_wrapper.sv
Labels: enhancement

#330 Add Hemaia Configs
  .github/workflows/ci.yml
  target/snitch_cluster/Makefile
  target/snitch_cluster/cfg/snax_alu.hjson
  target/snitch_cluster/cfg/snax_dimc.hjson
  target/snitch_cluster/cfg/snax_hypercorex.hjson
  target/snitch_cluster/cfg/snax_kul_cluster_mixed_narrow_wide.hjson
  target/snitch_cluster/cfg/snax_kul_cluster_mixed_narrow_wide_xdma.hjson
  target/snitch_cluster/cfg/snax_mac.hjson
  target/snitch_cluster/cfg/snax_mac_mult.hjson
  target/snitch_cluster/cfg/snax_streamer_gemm.hjson
  target/snitch_cluster/cfg/snax_streamer_gemm_add_c.hjson
  target/snitch_cluster/sw/Makefile
  target/snitch_cluster/sw/apps/Makefile
Labels: clean up

#332 Change config names in docker
  util/container/Dockerfile
Labels: bug, clean up

#333 Add disable switch for header files
  target/snitch_cluster/Makefile
  util/snaxgen/snaxgen.py
Labels: clean up

#339 Use remote snitch icache
  Bender.yml
  hw/snitch_cluster/src/snitch_cluster.sv
  hw/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral.sv
  hw/snitch_cluster/src/snitch_hive.sv
  hw/snitch_icache/.gitignore
  hw/snitch_icache/doc/index.md
  hw/snitch_icache/src/snitch_icache.sv
  hw/snitch_icache/src/snitch_icache_data.sv
  hw/snitch_icache/src/snitch_icache_handler.sv
  hw/snitch_icache/src/snitch_icache_l0.sv
  hw/snitch_icache/src/snitch_icache_lfsr.sv
  hw/snitch_icache/src/snitch_icache_lookup.sv
  hw/snitch_icache/src/snitch_icache_pkg.sv
  hw/snitch_icache/src/snitch_icache_refill.sv
  hw/snitch_icache/src/snitch_icache_tag.sv
  hw/snitch_icache/test/snitch_icache_l0_tb.sv
  hw/snitch_icache/util/compile.sh
  hw/snitch_icache/util/run_vsim.sh
  target/common/common.mk
Labels: enhancement, clean up

#349 Add cluster cuts
  hw/snitch_cluster/src/snitch_cluster.sv
  target/snitch_cluster/cfg/snax_alu.hjson
  target/snitch_cluster/cfg/snax_dimc.hjson
  target/snitch_cluster/cfg/snax_hypercorex.hjson
  target/snitch_cluster/cfg/snax_kul_cluster_mixed_narrow_wide.hjson
  target/snitch_cluster/cfg/snax_kul_cluster_mixed_narrow_wide_xdma.hjson
  target/snitch_cluster/cfg/snax_mac.hjson
  target/snitch_cluster/cfg/snax_mac_mult.hjson
  target/snitch_cluster/cfg/snax_streamer_gemm.hjson
  target/snitch_cluster/cfg/snax_streamer_gemm_add_c.hjson
Labels: enhancement
