Repository KULeuven-MICAS/snax_cluster, pull requests merged in 2024-08, with the labels that each got.

#209 Fix Snitch cluster CI
  hw/snitch_cluster/src/snitch_cc.sv
Labels: bug

#211 Set Verilator version v5.006
  util/container/Dockerfile
Labels: clean up

#212 Merge bypass signal of xdma extension
  .github/workflows/lint.yml
  hw/chisel/src/main/scala/snax/xdma/xdmaExtension/DMAExtension.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaFrontend/DMACtrl.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaFrontend/DMADataPath.scala
  hw/chisel/src/main/scala/snax/xdma/xdmaTop/xdmaTop.scala
  hw/chisel/src/test/scala/snax/xdma/xdmaExtension/DMAExtensionTester.scala
  hw/chisel/src/test/scala/snax/xdma/xdmaTop/xdmaTopTester.scala
  target/snitch_cluster/sw/snax/xdma/include/snax-xdma-csr-addr.h
  target/snitch_cluster/sw/snax/xdma/src/snax-xdma-lib.c
Labels: enhancement

#215 Revert "Use verilator v5.006 (#211)"
  util/container/Dockerfile
Labels: bug

#219 fix CFG_FILE variable inside Makefile to have correct absolute directory of CFG_OVERRIDE
  target/snitch_cluster/Makefile
Labels: clean up

#217 Adding `rtl-gen` to the docker builds
  util/container/Dockerfile
Labels: bug

#218 Separating cluster name targets for ease of use in top-level integration
  Bender.yml
  target/snitch_cluster/Makefile
  target/snitch_cluster/cfg/snax-streamer-gemm-conv.hjson
  target/snitch_cluster/cfg/snax-wide-gemm-data-reshuffler.hjson
Labels: enhancement, clean up

#223 Setting AXI version in bender to be fixed to 0.39.1
  Bender.local
Labels: clean up

#222 Synthesis switches for memory
  hw/snitch_cluster/src/snitch_data_mem.sv
  hw/snitch_icache/src/snitch_icache_data.sv
  hw/snitch_icache/src/snitch_icache_tag.sv
Labels: clean up

#224 Combine Chisel generation with SNAX gen
  hw/chisel_acc/Makefile
  hw/chisel_acc/build.sc
  target/snitch_cluster/Makefile
  util/snaxgen/snaxgen.py
Labels: enhancement, clean up

#213 Initial addition of the Hypercorex
  .github/workflows/ci.yml
  Bender.yml
  hw/snax_hypercorex/snax_hypercorex_shell_wrapper.sv
  target/snitch_cluster/Makefile
  target/snitch_cluster/cfg/snax-hypercorex.hjson
Labels: enhancement

#227 Clean-up double driven signal and declaration of generated directory
  hw/templates/snax_streamer_wrapper.sv.tpl
  target/snitch_cluster/Makefile
Labels: bug, clean up

#230 Add initial CSR test for Hypercorex
  .github/workflows/ci.yml
  sw/snRuntime/src/csr.h
  target/snitch_cluster/sw/Makefile
  target/snitch_cluster/sw/apps/Makefile
  target/snitch_cluster/sw/apps/snax-hypercorex/Makefile
  target/snitch_cluster/sw/apps/snax-hypercorex/test-csr/Makefile
  target/snitch_cluster/sw/apps/snax-hypercorex/test-csr/data/data.h
  target/snitch_cluster/sw/apps/snax-hypercorex/test-csr/src/test-csr.c
  target/snitch_cluster/sw/snax-hypercorex-run.yaml
  target/snitch_cluster/sw/snax/hypercorex/Makefile
  target/snitch_cluster/sw/snax/hypercorex/include/snax-hypercorex-csr.h
  target/snitch_cluster/sw/snax/hypercorex/include/snax-hypercorex-lib.h
  target/snitch_cluster/sw/snax/hypercorex/src/snax-hypercorex-lib.c
Labels: enhancement

#232 Add harness target switch
  Bender.yml
  target/snitch_cluster/Makefile
Labels: clean up

#235 Xyi/fix gemmx loopnum
  target/snitch_cluster/cfg/snax-streamer-gemmX-xdma.hjson
  target/snitch_cluster/cfg/snax-streamer-gemmX.hjson
Labels: bug

#249 Add custom TCDM assignment feature
  docs/schema/snitch_cluster.schema.json
  hw/snitch_cluster/src/snitch_cluster.sv
  hw/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
  target/snitch_cluster/cfg/snax-hypercorex.hjson
Labels: enhancement

#252 Checking streamer CSR RW capabilities for Hypercorex
  target/snitch_cluster/cfg/snax-hypercorex.hjson
  target/snitch_cluster/sw/apps/snax-hypercorex/test-csr/data/data.h
  target/snitch_cluster/sw/apps/snax-hypercorex/test-csr/src/test-csr.c
  target/snitch_cluster/sw/snax/hypercorex/include/snax-hypercorex-csr.h
  target/snitch_cluster/sw/snax/hypercorex/include/snax-hypercorex-lib.h
  target/snitch_cluster/sw/snax/hypercorex/src/snax-hypercorex-lib.c
Labels: enhancement

#256 Hypercorex Character Recognition Test
  .github/workflows/ci.yml
  target/snitch_cluster/sw/apps/Makefile
  target/snitch_cluster/sw/apps/snax-hypercorex/char-recog/Makefile
  target/snitch_cluster/sw/apps/snax-hypercorex/char-recog/data/Makefile
  target/snitch_cluster/sw/apps/snax-hypercorex/char-recog/data/datagen.py
  target/snitch_cluster/sw/apps/snax-hypercorex/char-recog/data/test_char_recog_asm.txt
  target/snitch_cluster/sw/apps/snax-hypercorex/char-recog/data/train_char_recog_asm.txt
  target/snitch_cluster/sw/apps/snax-hypercorex/char-recog/src/char-recog.c
  target/snitch_cluster/sw/snax/hypercorex/include/snax-hypercorex-lib.h
  target/snitch_cluster/sw/snax/hypercorex/src/snax-hypercorex-lib.c
Labels: enhancement

#257 Add hypercorex char recog to CI run
  target/snitch_cluster/sw/snax-hypercorex-run.yaml
Labels: clean up

#258 Fix template bit-width error for Questasim
  hw/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
Labels: bug

#259 Fix missing array index (outer index) for the bit signal in memory.
  hw/snitch_cluster/src/snitch_data_mem.sv
Labels: bug

#262 Clean-up: Fix Hypercorex bit-width errors, initial assertion after reset, Hypercorex wide access stride
  hw/snax_hypercorex/snax_hypercorex_shell_wrapper.sv
  hw/snitch_cluster/src/snitch_cc.sv
  target/snitch_cluster/sw/apps/snax-hypercorex/char-recog/src/char-recog.c
Labels: bug, clean up

#264 Set default AXI user widths to 2
  docs/schema/snitch_cluster.schema.json
Labels: clean up

#265 Modify testharness configurations
  hw/templates/testharness.sv.tpl
  util/snaxgen/snaxgen.py
Labels: bug, clean up

#266 Updating docs for new rtl-gen instructions and QuestaSim build
  docs/tutorial/build_system.md
  docs/tutorial/csrman_design.md
  docs/tutorial/other_tools.md
  docs/tutorial/streamer_design.md
  docs/tutorial/summary_and_exercise.md
Labels: documentation

#269 fix logic bug in gemmx
  hw/chisel_acc/src/main/scala/snax_acc/gemm/BlockGemm.scala
  hw/chisel_acc/src/main/scala/snax_acc/gemm_simd/BlockGemmRescaleSIMD.scala
  hw/chisel_acc/src/main/scala/snax_acc/simd/PipelinedRescaleSIMD.scala
  hw/chisel_acc/src/main/scala/snax_acc/simd/RescaleSIMD.scala
Labels: bug

#274 Take out `snax-gemm` from Docker build
  util/container/Dockerfile
Labels: clean up

#276 Add make file targets for synthesis generation
  target/common/common.mk
  target/snitch_cluster/Makefile
Labels: enhancement

#280 fix-testharness-tlp-for-questasim
  hw/templates/testharness.sv.tpl
Labels: bug, clean up

#287 Add `snax_mac` target to bender
  Bender.yml
  hw/snax_util/src/snax_intf_translator.sv
Labels: clean up

#289 Make dependency order only
  target/snitch_cluster/Makefile
Labels: clean up

#290 Modify memories to default `tc_sram_impl`
  hw/snitch_cluster/src/snitch_data_mem.sv
  hw/snitch_icache/src/snitch_icache_data.sv
  hw/snitch_icache/src/snitch_icache_tag.sv
Labels: clean up
