Repository KULeuven-MICAS/snax_cluster, pull requests merged in 2025-03, with the labels that each got.

#423 use pixi-defined docker container
  pixi.lock
  pixi.toml
  util/container/Dockerfile
Labels: enhancement

#446 Update documentation for first half of the year of 2025 part 1
  README.md
  docs/tutorial/accelerator_design.md
  docs/tutorial/build_system.md
  docs/tutorial/introduction.md
  docs/tutorial/streamer_design.md
  docs/ug/getting_started.md
  mkdocs.yml
Labels: documentation, clean up

#453 Fix-sbt-test-ci
  .github/workflows/scala-unit-test.yml
  hw/chisel/src/main/scala/snax/streamer/StreamParamGen.scala
Labels: clean up
